version: "3.8"
services:
 sinatrends-backend:
  build:
   context: "."
   dockerfile: "Dockerfile"
  restart: always
  ports:
   - "8081:8080"
  depends_on:
   - sinatrends-db
  env_file:
  - .env 
 sinatrends-db:
  image: mysql:8.0
  restart: always
  ports:
   - "3308:3306"
  environment:
   MYSQL_ROOT_PASSWORD: ${DB_PASS}
   MYSQL_DATABASE: ${DB_NAME}
   MYSQL_USER: ${DB_USER}
   MYSQL_PASSWORD: ${DB_PASS}
  volumes:
   - mysql_data:/var/lib/mysql
  env_file:
  - .env     
volumes:
 mysql_data: