spring.application.name=sinatrends

#Mysql configuration
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sinatrends
spring.datasource.username=root
spring.datasource.password=demopass@123
spring.web.resources.static-locations=file:uploads/

#Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true